### ISSUE TITLE
Improvement Error Handling

### ISSUE THREAD

**Issue by jpmartha** [JPMartha/EggsBenedict#20]
`SharingFlowError`

``` swift
} catch let error as NSError {
    completion?(sharingFlowResult: .Failure(self.imagePath, error))
```

https://github.com/JPMartha/EggsBenedict/blob/develop/EggsBenedict/SharingFlow.swift#L115-L116

And, I think it is not necessary to implement the following:

``` swift
guard !self.imagePath.isEmpty else {
    completion?(sharingFlowResult: .Failure(self.imagePath, SharingFlowError.ImagePathIsEmpty))
    return
}
```

https://github.com/JPMartha/EggsBenedict/blob/develop/EggsBenedict/SharingFlow.swift#L125-L128

**Comment by JPMartha** [comment]
`SharingFlowError`
https://github.com/JPMartha/EggsBenedict/blob/develop/EggsBenedict/SharingFlow.swift#L115-L116

And, I think it is not necessary to implement the following:
https://github.com/JPMartha/EggsBenedict/blob/develop/EggsBenedict/SharingFlow.swift#L125-L128
